package com.example.constant;

public enum ProductTypeConstant {
	BEBIDA, ALIMENTO, ELECTRODOMESTICO, CONSTRUCCION, AUTOMOTOR,
	HIEGIENE, LIMPIEZA, DECORACION, INDUMENTARIA, EDUCACION,
	TECNOLOGIA;
}
